### ISSUE TITLE
set/rm entrypoint (package.entrypoints)

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-flow-api#5]

**Comment by ottiker** [comment]
Since the `entrypoints` are handled by [jillix/engine](https://github.com/jillix/engine/blob/master/lib/flow.server.js#L57-L64) and configured in the applications `package.json`, this issue belongs to the [service-api](https://github.com/jillix/service-api).

**Comment by IonicaBizau** [comment]
We should use the entrypoint manager in service-api: https://github.com/jillix/engine-entrypoint-manager
